// <auto-generated />
using System;
using JoyReactor.Accordion.Logic.Database.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JoyReactor.Accordion.Workers.Migrations
{
    [DbContext(typeof(SqlDatabaseContext))]
    [Migration("20260101211357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedBandCamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlbumId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostAttributeEmbededId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostAttributeEmbededId");

                    b.HasIndex("AlbumId")
                        .IsUnique();

                    b.ToTable("ParsedBandCamps");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedCoub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostAttributeEmbededId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostAttributeEmbededId");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("ParsedCoubs");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NumberId")
                        .IsUnique();

                    b.ToTable("ParsedPost");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributeEmbeded", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BandCampId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SoundCloudId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VimeoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("YouTubeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BandCampId")
                        .IsUnique();

                    b.HasIndex("CoubId")
                        .IsUnique();

                    b.HasIndex("SoundCloudId")
                        .IsUnique();

                    b.HasIndex("VimeoId")
                        .IsUnique();

                    b.HasIndex("YouTubeId")
                        .IsUnique();

                    b.HasIndex("PostId", "BandCampId", "CoubId", "SoundCloudId", "VimeoId", "YouTubeId")
                        .IsUnique();

                    b.ToTable("ParsedPostAttributeEmbeds");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributePicture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVectorCreated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VectorLastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsVectorCreated");

                    b.HasIndex("PostId", "AttributeId")
                        .IsUnique();

                    b.ToTable("ParsedPostAttributePictures");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedSoundCloud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostAttributeEmbededId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UrlPath")
                        .IsUnique();

                    b.ToTable("ParsedSoundClouds");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MainTagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubTagsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriberCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MainTagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NumberId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ParsedTags");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedVimeo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostAttributeEmbededId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("ParsedVimeos");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedYoutube", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostAttributeEmbededId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("ParsedYoutubes");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributeEmbeded", b =>
                {
                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedBandCamp", "BandCamp")
                        .WithOne("PostAttributeEmbeded")
                        .HasForeignKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributeEmbeded", "BandCampId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedCoub", "Coub")
                        .WithOne("PostAttributeEmbeded")
                        .HasForeignKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributeEmbeded", "CoubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPost", "Post")
                        .WithMany("AttributeEmbeds")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedSoundCloud", "SoundCloud")
                        .WithOne("PostAttributeEmbeded")
                        .HasForeignKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributeEmbeded", "SoundCloudId")
                        .HasPrincipalKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedSoundCloud", "PostAttributeEmbededId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedVimeo", "Vimeo")
                        .WithOne("PostAttributeEmbeded")
                        .HasForeignKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributeEmbeded", "VimeoId")
                        .HasPrincipalKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedVimeo", "PostAttributeEmbededId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedYoutube", "YouTube")
                        .WithOne("PostAttributeEmbeded")
                        .HasForeignKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributeEmbeded", "YouTubeId")
                        .HasPrincipalKey("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedYoutube", "PostAttributeEmbededId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BandCamp");

                    b.Navigation("Coub");

                    b.Navigation("Post");

                    b.Navigation("SoundCloud");

                    b.Navigation("Vimeo");

                    b.Navigation("YouTube");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPostAttributePicture", b =>
                {
                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPost", "Post")
                        .WithMany("AttributePictures")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedTag", b =>
                {
                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedTag", "MainTag")
                        .WithMany("Synonyms")
                        .HasForeignKey("MainTagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedTag", "Parent")
                        .WithMany("SubTags")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MainTag");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedBandCamp", b =>
                {
                    b.Navigation("PostAttributeEmbeded")
                        .IsRequired();
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedCoub", b =>
                {
                    b.Navigation("PostAttributeEmbeded")
                        .IsRequired();
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedPost", b =>
                {
                    b.Navigation("AttributeEmbeds");

                    b.Navigation("AttributePictures");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedSoundCloud", b =>
                {
                    b.Navigation("PostAttributeEmbeded")
                        .IsRequired();
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedTag", b =>
                {
                    b.Navigation("SubTags");

                    b.Navigation("Synonyms");
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedVimeo", b =>
                {
                    b.Navigation("PostAttributeEmbeded")
                        .IsRequired();
                });

            modelBuilder.Entity("JoyReactor.Accordion.Logic.Database.Sql.Entities.ParsedYoutube", b =>
                {
                    b.Navigation("PostAttributeEmbeded")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
